class Schedule:
    """
    Schedule is a list of itinerary generated by the scheduler and will be used
    by the simulation for simulating the next airport state. The schedule
    should *ONLY* contains the new itineraries that the aircrafts don't obtain.
    """

    """
    aircraft_itineraries = [ { aircraft : itinerary } ]
    """
    def __init__(self, aircraft_itineraries):
        self.aircraft_itineraries = aircraft_itineraries
