class Schedule:
    """
    Schedule is a list of itinerary generated by the scheduler and will be used
    by the simulation for simulating the next airport state. The schedule
    should *ONLY* contains the new itineraries that the aircrafts don't obtain.
    """

    class Request:
        def __init__(self, aircraft, itinerary):
            self.aircraft = aircraft
            self.itinerary = itinerary

    def __init__(self, requests, tightness):
        self.requests = requests
        self.tightness = tightness