class Schedule:
    """
    Schedule is a list of itinerary generated by the scheduler and will be used
    by the simulation for simulating the next airport state. The schedule
    should *ONLY* contains the new itineraries that the aircrafts don't obtain.

    The scheduler can also pass a list of flights that have been delayed beyond 
    the current scheduling window in the form of (aircraft, delayed_time) tuples
    """

    class Request:
        def __init__(self, aircraft, itinerary):
            self.aircraft = aircraft
            self.itinerary = itinerary

    def __init__(self, requests, delayed_aircrafts, tightness):
        self.requests = requests
        self.delayed_aircrafts = delayed_aircrafts
        self.tightness = tightness